export const CoursesData = () => {
  const CoursesData = [
    {
      id: 1,
      img: "01",
      folder: "CoursesDetails",
      title: "React js",
      des: "اموزشگاه در تدارک تولید دوره ی جدید برنامه نویسی است",
      mainDes:
        "ری اکت یکی از کتابخانه های اوپن سورس (متن باز) جاوا اسکریپت هست که طبق گفته داکیومنت خود آن برای ساخت رابط های کاربری وب سایت ها مورد استفاده قرار می گیرد.کتابخانه ری اکت توسط جامعه ای از توسعه دهندگان فیس بوک ارائه شد. ریکت ابتدا در سال 2011 با هدف استفاده توسط خود فیسبوک ایجاد شد اما بعد ها با توسعه بیشتر و تکمیل شدنش در سال 2013 به یک کتابخانه عمومی برای استفاده همه برنامه نویس ها تبدیل شد",
      blogKind: "اموزشی",
      name: "CoursesDetails",
      teacher: "استاد بحر",
      cousersTime: "30ساعت",
      likeNumber: "30",
      cost: "300,000تومان",
      deleteicon: "bi-trash",
      addicon: "bi-plus-circle-fill",
      corsesName: "React",
      sesion: "بهار",
      startDate: "1400/12/20",
      endDate: "1401/01/01",
    },
    {
      id: 2,
      img: "01",
      folder: "CoursesDetails",
      title: "React js",
      des: "اموزشگاه در تدارک تولید دوره ی جدید برنامه نویسی است",
      mainDes:
        "ری اکت یکی از کتابخانه های اوپن سورس (متن باز) جاوا اسکریپت هست که طبق گفته داکیومنت خود آن برای ساخت رابط های کاربری وب سایت ها مورد استفاده قرار می گیرد.کتابخانه ری اکت توسط جامعه ای از توسعه دهندگان فیس بوک ارائه شد. ریکت ابتدا در سال 2011 با هدف استفاده توسط خود فیسبوک ایجاد شد اما بعد ها با توسعه بیشتر و تکمیل شدنش در سال 2013 به یک کتابخانه عمومی برای استفاده همه برنامه نویس ها تبدیل شد",
      blogKind: "اموزشی",
      name: "CoursesDetails",
      teacher: "استاد بحر",
      cousersTime: "30ساعت",
      likeNumber: "30",
      cost: "300,000تومان",
      deleteicon: "bi-trash",
      addicon: "bi-plus-circle-fill",
      corsesName: "React",
      sesion: "بهار",
      startDate: "1400/12/20",
      endDate: "1401/01/01",
    },
    {
      id: 3,
      img: "01",
      folder: "CoursesDetails",
      title: "React js",
      des: "اموزشگاه در تدارک تولید دوره ی جدید برنامه نویسی است",
      mainDes:
        "ری اکت یکی از کتابخانه های اوپن سورس (متن باز) جاوا اسکریپت هست که طبق گفته داکیومنت خود آن برای ساخت رابط های کاربری وب سایت ها مورد استفاده قرار می گیرد.کتابخانه ری اکت توسط جامعه ای از توسعه دهندگان فیس بوک ارائه شد. ریکت ابتدا در سال 2011 با هدف استفاده توسط خود فیسبوک ایجاد شد اما بعد ها با توسعه بیشتر و تکمیل شدنش در سال 2013 به یک کتابخانه عمومی برای استفاده همه برنامه نویس ها تبدیل شد",
      blogKind: "اموزشی",
      name: "CoursesDetails",
      teacher: "استاد بحر",
      cousersTime: "30ساعت",
      likeNumber: "30",
      cost: "300,000تومان",
      deleteicon: "bi-trash",
      addicon: "bi-plus-circle-fill",
      corsesName: "React",
      sesion: "بهار",
      startDate: "1400/12/20",
      endDate: "1401/01/01",
    },
    {
      id: 4,
      img: "01",
      folder: "CoursesDetails",
      title: "React js",
      des: "اموزشگاه در تدارک تولید دوره ی جدید برنامه نویسی است",
      mainDes:
        "ری اکت یکی از کتابخانه های اوپن سورس (متن باز) جاوا اسکریپت هست که طبق گفته داکیومنت خود آن برای ساخت رابط های کاربری وب سایت ها مورد استفاده قرار می گیرد.کتابخانه ری اکت توسط جامعه ای از توسعه دهندگان فیس بوک ارائه شد. ریکت ابتدا در سال 2011 با هدف استفاده توسط خود فیسبوک ایجاد شد اما بعد ها با توسعه بیشتر و تکمیل شدنش در سال 2013 به یک کتابخانه عمومی برای استفاده همه برنامه نویس ها تبدیل شد",
      blogKind: "اموزشی",
      name: "CoursesDetails",
      teacher: "استاد بحر",
      cousersTime: "30ساعت",
      likeNumber: "30",
      cost: "300,000تومان",
      deleteicon: "bi-trash",
      addicon: "bi-plus-circle-fill",
      corsesName: "React",
      sesion: "بهار",
      startDate: "1400/12/20",
      endDate: "1401/01/01",
    },
    {
      id: 5,
      img: "02",
      folder: "CoursesDetails",
      title: "sass",
      des: "اموزشگاه در تدارک تولید دوره ی جدید برنامه نویسی است",
      mainDes:
        "Sass مخفف کلمات Syntactically Awesome Stylesheets است. Sass را می توان به عنوان یک افزونه برای css در نظر گرفت که کار با استایل ها را برای ما بسیار ساده می کند. به خصوص زمانی که فایل های css شما بسیار بزرگ و پیچیده باشند. Sass مدیریت و نگهداری استایل های css را ساده‌تر می‌کند. به لطف وجود متغیرها، mixins ها، nesting ها و وراثت در این پیش پردازنده، کد های نوشته شده کاملاً سازماندهی می شود.",
      blogKind: "اموزشی",
      name: "CoursesDetails",
      teacher: "استاد بحر",
      cousersTime: "30ساعت",
      likeNumber: "30",
      cost: "300,000تومان",
      deleteicon: "bi-trash",
      addicon: "bi-plus-circle-fill",
      corsesName: "React",
      sesion: "بهار",
      startDate: "1400/12/20",
      endDate: "1401/01/01",
    },
    {
      id: 6,
      img: "02",
      folder: "CoursesDetails",
      title: "sass",
      des: "اموزشگاه در تدارک تولید دوره ی جدید برنامه نویسی است",
      mainDes:
        "Sass مخفف کلمات Syntactically Awesome Stylesheets است. Sass را می توان به عنوان یک افزونه برای css در نظر گرفت که کار با استایل ها را برای ما بسیار ساده می کند. به خصوص زمانی که فایل های css شما بسیار بزرگ و پیچیده باشند. Sass مدیریت و نگهداری استایل های css را ساده‌تر می‌کند. به لطف وجود متغیرها، mixins ها، nesting ها و وراثت در این پیش پردازنده، کد های نوشته شده کاملاً سازماندهی می شود.",
      blogKind: "اموزشی",
      name: "CoursesDetails",
      teacher: "استاد بحر",
      cousersTime: "30ساعت",
      likeNumber: "30",
      cost: "300,000تومان",
      deleteicon: "bi-trash",
      addicon: "bi-plus-circle-fill",
      corsesName: "React",
      sesion: "بهار",
      startDate: "1400/12/20",
      endDate: "1401/01/01",
    },
    {
      id: 7,
      img: "02",
      folder: "CoursesDetails",
      title: "sass",
      des: "اموزشگاه در تدارک تولید دوره ی جدید برنامه نویسی است",
      mainDes:
        "Sass مخفف کلمات Syntactically Awesome Stylesheets است. Sass را می توان به عنوان یک افزونه برای css در نظر گرفت که کار با استایل ها را برای ما بسیار ساده می کند. به خصوص زمانی که فایل های css شما بسیار بزرگ و پیچیده باشند. Sass مدیریت و نگهداری استایل های css را ساده‌تر می‌کند. به لطف وجود متغیرها، mixins ها، nesting ها و وراثت در این پیش پردازنده، کد های نوشته شده کاملاً سازماندهی می شود.",
      blogKind: "اموزشی",
      name: "CoursesDetails",
      teacher: "استاد بحر",
      cousersTime: "30ساعت",
      likeNumber: "30",
      cost: "300,000تومان",
      deleteicon: "bi-trash",
      addicon: "bi-plus-circle-fill",
      corsesName: "React",
      sesion: "بهار",
      startDate: "1400/12/20",
      endDate: "1401/01/01",
    },
    {
      id: 8,
      img: "02",
      folder: "CoursesDetails",
      title: "sass",
      des: "اموزشگاه در تدارک تولید دوره ی جدید برنامه نویسی است",
      mainDes:
        "Sass مخفف کلمات Syntactically Awesome Stylesheets است. Sass را می توان به عنوان یک افزونه برای css در نظر گرفت که کار با استایل ها را برای ما بسیار ساده می کند. به خصوص زمانی که فایل های css شما بسیار بزرگ و پیچیده باشند. Sass مدیریت و نگهداری استایل های css را ساده‌تر می‌کند. به لطف وجود متغیرها، mixins ها، nesting ها و وراثت در این پیش پردازنده، کد های نوشته شده کاملاً سازماندهی می شود.",
      blogKind: "اموزشی",
      name: "CoursesDetails",
      teacher: "استاد بحر",
      cousersTime: "30ساعت",
      likeNumber: "30",
      cost: "300,000تومان",
      deleteicon: "bi-trash",
      addicon: "bi-plus-circle-fill",
      corsesName: "React",
      sesion: "بهار",
      startDate: "1400/12/20",
      endDate: "1401/01/01",
    },
    {
      id: 9,
      img: "03",
      folder: "CoursesDetails",
      title: "vue js",
      des: "اموزشگاه در تدارک تولید دوره ی جدید برنامه نویسی است",
      mainDes:
        "ویو یک فریم‌ورک متن باز زبان javascript است که از آن برای توسعه رابط کاربری استفاده می­‌شود. Vue.js برای اولین بار در دسامبر سال 2013 توسط Evan You، یکی از کارمندان سابق گوگل، به دنیا معرفی شد. ایوان که در شغل پیشین خود از فریم­ورک Angular js در توسعه برنامه‌­ها استفاده می‌کرد، تصمیم گرفت تا فریم‌ورکی برای استفاده در پروژه‌­های خود خلق کند که به اندازه Angular قدرتمند و در عین حال سبک‌وزن و انعطاف‌پذیر باشد",
      blogKind: "اموزشی",
      name: "CoursesDetails",
      teacher: "استاد بحر",
      cousersTime: "30ساعت",
      likeNumber: "30",
      cost: "300,000تومان",
      deleteicon: "bi-trash",
      addicon: "bi-plus-circle-fill",
      corsesName: "React",
      sesion: "بهار",
      startDate: "1400/12/20",
      endDate: "1401/01/01",
    },
    {
      id: 10,
      img: "03",
      folder: "CoursesDetails",
      title: "vue js",
      des: "اموزشگاه در تدارک تولید دوره ی جدید برنامه نویسی است",
      mainDes:
        "ویو یک فریم‌ورک متن باز زبان javascript است که از آن برای توسعه رابط کاربری استفاده می­‌شود. Vue.js برای اولین بار در دسامبر سال 2013 توسط Evan You، یکی از کارمندان سابق گوگل، به دنیا معرفی شد. ایوان که در شغل پیشین خود از فریم­ورک Angular js در توسعه برنامه‌­ها استفاده می‌کرد، تصمیم گرفت تا فریم‌ورکی برای استفاده در پروژه‌­های خود خلق کند که به اندازه Angular قدرتمند و در عین حال سبک‌وزن و انعطاف‌پذیر باشد",
      blogKind: "اموزشی",
      name: "CoursesDetails",
      teacher: "استاد بحر",
      cousersTime: "30ساعت",
      likeNumber: "30",
      cost: "300,000تومان",
      deleteicon: "bi-trash",
      addicon: "bi-plus-circle-fill",
      corsesName: "React",
      sesion: "بهار",
      startDate: "1400/12/20",
      endDate: "1401/01/01",
    },
    {
      id: 11,
      img: "03",
      folder: "CoursesDetails",
      title: "vue js",
      des: "اموزشگاه در تدارک تولید دوره ی جدید برنامه نویسی است",
      mainDes:
        "ویو یک فریم‌ورک متن باز زبان javascript است که از آن برای توسعه رابط کاربری استفاده می­‌شود. Vue.js برای اولین بار در دسامبر سال 2013 توسط Evan You، یکی از کارمندان سابق گوگل، به دنیا معرفی شد. ایوان که در شغل پیشین خود از فریم­ورک Angular js در توسعه برنامه‌­ها استفاده می‌کرد، تصمیم گرفت تا فریم‌ورکی برای استفاده در پروژه‌­های خود خلق کند که به اندازه Angular قدرتمند و در عین حال سبک‌وزن و انعطاف‌پذیر باشد",
      blogKind: "اموزشی",
      name: "CoursesDetails",
      teacher: "استاد بحر",
      cousersTime: "30ساعت",
      likeNumber: "30",
      cost: "300,000تومان",
      deleteicon: "bi-trash",
      addicon: "bi-plus-circle-fill",
      corsesName: "React",
      sesion: "بهار",
      startDate: "1400/12/20",
      endDate: "1401/01/01",
    },
    {
      id: 12,
      img: "03",
      folder: "CoursesDetails",
      title: "vue js",
      des: "اموزشگاه در تدارک تولید دوره ی جدید برنامه نویسی است",
      mainDes:
        "ویو یک فریم‌ورک متن باز زبان javascript است که از آن برای توسعه رابط کاربری استفاده می­‌شود. Vue.js برای اولین بار در دسامبر سال 2013 توسط Evan You، یکی از کارمندان سابق گوگل، به دنیا معرفی شد. ایوان که در شغل پیشین خود از فریم­ورک Angular js در توسعه برنامه‌­ها استفاده می‌کرد، تصمیم گرفت تا فریم‌ورکی برای استفاده در پروژه‌­های خود خلق کند که به اندازه Angular قدرتمند و در عین حال سبک‌وزن و انعطاف‌پذیر باشد",
      blogKind: "اموزشی",
      name: "CoursesDetails",
      teacher: "استاد بحر",
      cousersTime: "30ساعت",
      likeNumber: "30",
      cost: "300,000تومان",
      deleteicon: "bi-trash",
      addicon: "bi-plus-circle-fill",
      corsesName: "React",
      sesion: "بهار",
      startDate: "1400/12/20",
      endDate: "1401/01/01",
    },
  ];
  return CoursesData;
};
